### PR TITLE
fix 'moveit_ros_control_interface' gazebo arm control

### PR DESCRIPTION
**Pull request by rickstaa**
This pull request shows how the `moveit_ros_control_interface::MoveItControllerManager` works. The most important thing is that you set the `ros_control_namespace` parameter within the `move_group` namespace. This controller manager however does not yet support the gripper action.

### CODE REVIEW

**Comment by rhaschke** [comment]
I don't yet see where the `ros_control_namespace` parameter is used. Can you provide a pointer to some code?
What happens if the parameter is not (correctly) set?

Closing here in favour of #14.

**Comment by rickstaa** [comment]
This behaviour is documented in the (outdated) [README](https://github.com/ros-planning/moveit/tree/master/moveit_plugins/moveit_ros_control_interface#setup) page of the `moveit_ros_control_interface`. The code that implements this can be found [here](https://github.com/ros-planning/moveit/blob/d1465a7dd55ffead03b35f9d0d3d878fc4757eeb/moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp#L187-L196). 

Do you want to update the README (i.e. remove the `controller_list` part) and explain the difference between the `moveit_ros_control_interface` and `moveit_simple_controller_manager` in the [Low-Level Controllers tutorial](https://ros-planning.github.io/moveit_tutorials/doc/controller_configuration/controller_configuration_tutorial.html). I can add a TODO for this.

**Comment by rickstaa** [comment]
Looks like @davetcoleman https://github.com/ros-planning/moveit/issues/112 already created an issue for this.

**Comment by rickstaa** [comment]
Here a quick summary for future reference:

When a controller manager is found in the root namespace, MoveIt can automatically find the trajectory controllers it should use (see [this code](https://github.com/ros-planning/moveit/blob/d1465a7dd55ffead03b35f9d0d3d878fc4757eeb/moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp#L187-L196)). When no controller manager is found, it throws the following error:

```bash
[/panda/move_group] [ WARN] [WallTime: 1635408493.753962593, 23.776000000]: Failed to read controllers from /controller_manager/list_controllers
[/panda/move_group] [ERROR] [WallTime: 1635408493.753997938, 23.776000000]: Unable to identify any set of controllers that can actuate the specified joints: [ panda_joint1 panda_joint2 panda_joint3 panda_joint4 panda_joint5 panda_joint6 panda_joint7 ]
[/panda/move_group] [ERROR] [WallTime: 1635408493.754017065, 23.776000000]: Known controllers and their joints:

[/panda/move_group] [ERROR] [WallTime: 1635408493.754036758, 23.776000000]: Apparently trajectory initialization failed
```

This can be solved by using the `moveit_ros_control_interface` parameter. This parameter points MoveIt to the controller manager, after which it can automatically find Trajectory controllers. It does not automatically find or work with any `GripperCommand` services. 

Further, the `controller_list` parameter seems to be ignored by the `moveit_ros_control_interface` in both cases.

**Pull request closed without merging**
