### PR TITLE
noetic-devel fixups

### PR DESCRIPTION
**Pull request by rhaschke**
See individual commits. Requires https://github.com/frankaemika/franka_ros/pull/188.

### CODE REVIEW

**Comment by rhaschke** [comment]
**franka_gazebo tests**
- [x] finger joints move in sync when setting target pose in MoveIt
- [x] finger joints move in sync when executing GripperCommands triggered from MoveIt, but action doesn't finish:
  ```
  [ERROR] ros.moveit_ros_planning.trajectory_execution_manager: Controller is taking too long to execute trajectory (the expected upper bound for the trajectory execution was 4.886437 seconds). Stopping trajectory.
  [ INFO] ros.moveit_simple_controller_manager.ActionBasedController: Cancelling execution for franka_gripper
  [ INFO] ros.moveit_ros_planning.trajectory_execution_manager: Completed trajectory execution with status TIMED_OUT ...
  [ INFO] ros.franka_gazebo.FrankaGripperSim: Gripper Command Action cancelled
  [ INFO] ros.moveit_ros_planning_interface.move_group_interface: ABORTED: Timeout reached
  ```
- [x] arm moves when triggered from MoveIt, but aborts (at the end) with `GOAL_TOLERANCE_VIOLATED`:
  ```
  [ WARN] ros.moveit_simple_controller_manager.SimpleControllerManager: Controller 'joint_trajectory_controller' failed with error GOAL_TOLERANCE_VIOLATED: 
  [ WARN] ros.moveit_ros_planning.trajectory_execution_manager: Controller handle joint_trajectory_controller reports status ABORTED
  [ INFO] ros.moveit_ros_planning.trajectory_execution_manager: Completed trajectory execution with status ABORTED ...
  [ INFO] ros.moveit_ros_planning_interface.move_group_interface: ABORTED: Solution found but controller failed during execution
  ```
- [x] spawning two models independently:
  ```
  roslaunch gazebo_ros empty_world.launch world_name:=worlds/empty.world use_sim_time:=true
  roslaunch franka_gazebo panda.launch gazebo:=false arm_id:=left ns:=left y:=0
  roslaunch franka_gazebo panda.launch gazebo:=false arm_id:=right ns:=right y:=1
  ```
- [x] spawning in a namespace:
  ```
  roslaunch franka_gazebo panda.launch ns:=foo controller:=joint_trajectory_controller
  ROS_NAMESPACE=foo roslaunch panda_moveit_config demo.launch load_robot_description:=false moveit_controller_manager:=simple
  ```

**Comment by rickstaa** [comment]
LGTM. Thanks for solving these issues! I tested everything except the `panda_moveit.launch` file. I will do this on Monday. Based on the code I however think there should be no problems other than the [PID gains](https://github.com/rhaschke/panda_moveit_config/blob/e9dd0c02bdc2e365a73dd49a46e6963c46840d25/config/ros_controllers.yaml#L11-L18) not being correct for the real robot. We however fix this when @frankaemika provides us with PID gains for the simulator and real robot.

> arm moves when triggered from MoveIt, but aborts (at the end) with GOAL_TOLERANCE_VIOLATED: 

I also noticed this during my tests. I tried to fix this with @gollth in https://github.com/frankaemika/franka_ros/pull/173 and https://github.com/frankaemika/franka_ros/pull/180. The issue however turned out to be a difficult one.

> spawning two models independently: 

Wow! Thanks for making this possible This is very helpful in my own research.

**Comment by rickstaa** [comment]
> Based on the code I however think there should be no problems other than the PID gains not being correct for the real robot. We however fix this when @frankaemika provides us with PID gains for the simulator and real robot.

I just saw you are already working don't this https://github.com/frankaemika/franka_ros/pull/186/files.

**Comment by rhaschke** [comment]
> Based on the code I however think there should be no problems other than the [PID gains](https://github.com/rhaschke/panda_moveit_config/blob/e9dd0c02bdc2e365a73dd49a46e6963c46840d25/config/ros_controllers.yaml#L11-L18) not being correct for the real robot. We however fix this when @frankaemika provides us with PID gains for the simulator and real robot.

The [real robot will (still) work with position controllers](https://github.com/frankaemika/franka_ros/blob/288a029bf73015988ef29ee7f7351463daa14708/franka_control/config/default_controllers.yaml#L2-L3), which doesn't require PID gains.

**Comment by rickstaa** [comment]
> > Based on the code I, however, think there should be no problems other than the [PID gains](https://github.com/rhaschke/panda_moveit_config/blob/e9dd0c02bdc2e365a73dd49a46e6963c46840d25/config/ros_controllers.yaml#L11-L18) not being correct for the real robot. ### We, however, fix this when @frankaemika provides us with PID gains for the simulator and real robot.
> 
> The [real robot will (still) work with position controllers](https://github.com/frankaemika/franka_ros/blob/288a029bf73015988ef29ee7f7351463daa14708/franka_control/config/default_controllers.yaml#L2-L3), which doesn't require PID gains.

I can test with the [joint_trajectory_controller](https://github.com/rhaschke/franka_ros/blob/26922707267d9e9a288a19d8d34be833edafae79/franka_control/config/default_controllers.yaml#L1-L26) controller on Monday. My point, however, was about the fact that currently, the `panda_arm_controller` is started, which is tuned for the simulation:

https://github.com/rhaschke/panda_moveit_config/blob/e9dd0c02bdc2e365a73dd49a46e6963c46840d25/launch/ros_controllers.launch#L8

In the future, we might want to start the effort PID controller provided by @frankaemika for the real robot. But let's wait till @frankaemika gives us with such a controller.

**Comment by rhaschke** [comment]
Actually, `ros_controllers.launch` and `*.yaml` are not used anymore in the latest proposal, because I switched to `moveit_controller_manager:=simple`. Thus, both in sim and real the `joint_trajectory_controller` should be used:
https://github.com/rhaschke/panda_moveit_config/blob/890134d0f43942f5dba2feb0bd1a6966ed37df39/config/simple_moveit_controllers.yaml#L2
started via `franka_gazebo`:
https://github.com/rhaschke/panda_moveit_config/blob/890134d0f43942f5dba2feb0bd1a6966ed37df39/launch/franka_gazebo.launch#L17

For the real robot you might need to add spawners for the controllers.

**Comment by rickstaa** [comment]
I like this solution! Now we provide all the required controllers but don't start them by default. All this control logic is now in the `franka_control` package. Users can then choose the controller they want to use. I will test on the real robot.

**Review by rickstaa — APPROVED** [review]

**Comment by rhaschke** [comment]
> Now we provide all the required controllers but don't start them by default. All this control logic is now in the `franka_control` package. Users can then choose the controller they want to use.

Yes, all controller configs are loaded as ROS params. But MoveIt's SimpleCtrlMngr requires the `joint_trajectory_controller` to be loaded _and started_. Otherwise:
`[ERROR] ros.joint_trajectory_controller.joint_trajectory_controller: Can't accept new action goals. Controller is not running.`

Only, the ROSCtrlMngr can start/stop controllers as well.

**Comment by rickstaa** [comment]
@rhaschke Good point! I didn't think of that. I will also test that and feedback the results to you. Feel free to join me on TeamViewer when I have all the tests set up.

**Comment by rickstaa** [comment]
@rhaschke I tested the `franka_control.launch` script on the real robot and it works (see gif). Based on my experiments and https://github.com/rhaschke/panda_moveit_config/pull/14#issuecomment-953871422 I would like to suggest automatically starting the `joint_trajectory_controller` (see #15).

robot_real_test

**Comment by rickstaa** [comment]
Maybe we can start the `joint_trajectory_controller` (i.e. effort-based) by default while the `joint_position_trajectory_controller` is only loaded by the  `franka_control` package. By doing this, we would adhere to @frankaemika's desire to use effort-based controllers as the default. This would require only a small change in https://github.com/frankaemika/franka_ros/pull/188/files.

**Pull request closed without merging**
